# Generated by Django 5.2.1 on 2025-05-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    '''Here's an instruction to Django, based on models.py, to create a model called Flight.
    It defines the Flight model that will create the initial database schema for the Flight model'''
    operations = [ 
        migrations.CreateModel( 
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=64)),
                ('destination', models.CharField(max_length=64)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
